### PR TITLE
Allow to override the http.Client for RequestToken and AccessToken

### PR DESCRIPTION
**Pull request by fdcds**
Before, the `http.DefaultClient` was always used.  This is e.g. not
sufficient, if the server being authenticated against uses TLS
certificates signed by a custom root CA.  In this case, a custom
`http.Client` needs to be passed.

To avoid passing arbitrary hidden objects through the context,
as can be seen sometimes in similar situations, the client
is passed through the `Config` struct instead.

### CODE REVIEW

**Comment by dghubble** [comment]
Thanks, but no thanks.

I've never liked how oauth2 uses the context for a client and I also wouldn't change the API for a case like this. If you have this situation, it's probably best you handle it on your own.

**Comment by fdcds** [comment]
> I've never liked how oauth2 uses the context for a client and I also wouldn't change the API for a case like this. If you have this situation, it's probably best you handle it on your own.

I agree with you that the way oauth2 passes a http.Client through the context does not spark much joy, to put it mildly. Do you have a suggestion how to do it better that would be acceptable to you? AFAIK the general recommendation is also to not use the http.DefaultClient, so that option also seems not a good solution either.

**Comment by dghubble** [comment]
A more ordinary approach is just setting a Client as a Config field and continue defaulting to http.DefaultClient on use. Or just do any approach on your own, where there is no need for compatibility and I'll call this out of scope.

**Comment by fdcds** [comment]
> A more ordinary approach is just setting a Client as a Config field and continue defaulting to http.DefaultClient on use.

Thanks. I implemented that in https://github.com/dghubble/oauth1/pull/49/commits/37256b95e8fb231e45d667be8f0d5fade885ba8a.

> Or just do any approach on your own, where there is no need for compatibility and I'll call this out of scope.

That would mean having to fork this fine library, which would be unfortunate. I would rather prefer to find a solution that is sound from an engineering point of view and merge it into your library.

**Pull request merged**
