### PR TITLE
Make noncer configurable via config

### PR DESCRIPTION
**Pull request by ezhdan-nyt**
Make `Noncer` configurable via `Config` to be able to provide custom noncer to generate unique random strings.

### CODE REVIEW

**Comment by dghubble** [comment]
Provide a rationale for exporting.

**Comment by ezhdan-nyt** [comment]
I've tried to use `oauth1` with another 3rd-party libraries that, unfortunately, do not support special characters in nonce (that's weird, I know). This is why I came up with idea to make `Noncer` configurable and custom.

My `CustomNoncer` looks like this:
```
package main

import "math/rand"

type CustomNoncer struct{
	nonce string
}

const alphaNumericBytes = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

func randStringBytes(n int) string {
	b := make([]byte, n)
	for i := range b {
		b[i] = alphaNumericBytes[rand.Intn(len(alphaNumericBytes))]
	}
	return string(b)
}

func (c CustomNoncer) Nonce() string {
	return randStringBytes(32)
}
```

**Comment by dghubble** [comment]
The nonce is `encoding/base64` with [StdEncoding](https://golang.org/pkg/encoding/base64/#pkg-variables) - the only "special" characters you'll find are `/`, `+`, and `=`. Which one does the 3rd-party library not allow? I could maybe see a case for the URLEncoding (`-`, `_`, `=`).

I'd prefer users not write their own noncers and it remain internal. Given the opportunity to implement a noncer poorly, someone will implement it poorly (e.g. fixed string). Currently such mistakes aren't allowed.

Btw, prefer `crypto/rand` in a case like this, not `math/rand`.

**Comment by ezhdan-nyt** [comment]
Yes, in my case it was the URLEncoding stuff from 3rd-party libraries side :(
Also, I got your point related to the possibility of improper noncer usage by user.

Btw, make your decision on this PR to oath1 repo, I am fine if you close it due to your concerns. I can use a fork with custom noncer.

P.S. Thanks for pointing to `crypto` versus `math`.

**Comment by dghubble** [comment]
This library uses base64 `StdEncoding`. But my question is which characters the 3rd-party (to me unknown) library disallowed. If you edit `StdEncoding` to `URLEncoding` does that resolve it? That would be a more agreeable change.

https://github.com/dghubble/oauth1/blob/master/auther.go#L145

**Pull request closed without merging**
